Repository oiooeo/glog, pull requests merged in 2023-09, with the labels that each got.

#94 design. 검색 목록 로그인 유도 버튼 & 게시글 작성 위치 수정 화면
  src/components/common/button/style.ts
  src/components/common/overlay/modal/style.ts
  src/components/common/postItem/style.ts
  src/components/like/style.ts
  src/components/post/Post.ContentsSection.tsx
  src/components/post/Post.tsx
  src/components/searchList/SearchList.SessionDependentView.tsx
  src/components/searchList/SearchList.tsx
  src/components/searchList/SearchList.util.tsx
  src/components/searchList/style.ts
Labels: design

#95 feat. Loading 추가
  src/components/globe/style.ts
  src/components/loading/Loading.tsx
  src/components/loading/style.ts
  src/pages/Home.tsx
Labels: enhancement

#96 design. 이미지 업로드 박스 수정, 파비콘 수정
  public/favicon.svg
  src/components/post/Post.UploadBox.tsx
  src/components/post/style.ts
Labels: design

#97 design.post 사진 토스트 메시지
  src/components/post/Post.UploadBox.tsx
  src/components/post/Post.tsx
  src/hooks/useImageUpload.ts
  src/index.css
Labels: design

#98 refactor. 코드 리팩토링 및 구조 변경
  src/components/common/header/Header.hooks.tsx
  src/components/common/header/Header.tsx
  src/components/globe/Globe.tsx
  src/components/globeCluster/GlobeCluster.tsx
  src/components/globeCluster/GlobeCluster.util.ts
  src/components/globeSearch/GlobeSearch.SearchBox.tsx
  src/components/globeSearch/GlobeSearch.tsx
  src/components/landing/Landing.tsx
  src/components/landing/style.ts
  src/components/post/Post.UploadBox.tsx
  src/components/post/Post.hooks.ts
  src/components/post/Post.tsx
  src/pages/Home.tsx
Labels: documentation

#99 fix. post.hooks.ts 컴포넌트 이름 수정
  src/components/post/Post.hooks.ts
  src/components/post/Post.tsx
Labels: fix

#100 fix. Landing 오류 수정
  src/components/landing/Landing.tsx
  src/components/landing/style.ts
Labels: bug

#102 docs. 리드미 수정
  README.md
Labels: documentation

#104 docs. 리드미 수정
  README.md
Labels: documentation

#105 dev to main
  README.md
Labels: documentation

#106 docs. zoomSize 문서 변경
  src/components/globeCluster/GlobeCluster.tsx
Labels: documentation

#107 docs. 리드미 수정
  README.md
Labels: documentation

#108 Dev to main
  README.md
Labels: documentation

#109 refactor. html 파일 수정
  public/index.html
  src/components/globeCluster/GlobeCluster.tsx
Labels: documentation

#110 design. 게시글 수정
  src/components/common/button/style.ts
  src/components/post/Post.ContentsSection.tsx
Labels: design

#111 refactor. ESlint 적용
  .eslintrc.json
  package.json
  src/App.tsx
  src/api/supabaseClient.ts
  src/api/supabaseDatabase.ts
  src/components/common/button/Button.tsx
  src/components/common/button/style.ts
  src/components/common/footer/Footer.tsx
  src/components/common/header/Header.hooks.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/HeaderLogin.tsx
  src/components/common/header/HeaderSearch.tsx
  src/components/common/overlay/Overlay.context.tsx
  src/components/common/overlay/modal/Modal.hooks.tsx
  src/components/common/overlay/modal/Modal.tsx
  src/components/common/postItem/PostItem.tsx
  src/components/common/switch/Switch.tsx
  src/components/detail/Detail.tsx
  src/components/globe/Globe.tsx
  src/components/globe/globe.util.tsx
  src/components/globeCluster/GlobeCluster.tsx
  src/components/globeSearch/GlobeSearch.SearchBox.tsx
  src/components/globeSearch/GlobeSearch.tsx
  src/components/landing/Landing.tsx
  src/components/like/Like.hooks.ts
  src/components/like/Like.tsx
  src/components/likesList/LikesList.tsx
  src/components/post/Post.ContentsSection.tsx
  src/components/post/Post.UploadBox.tsx
  src/components/post/Post.hooks.ts
  src/components/post/Post.tsx
  src/components/post/Post.util.tsx
  src/components/post/style.ts
  src/components/searchList/SearchList.SessionDependentView.tsx
  src/components/searchList/SearchList.tsx
  src/components/searchList/SearchList.util.tsx
  src/hooks/useInput.tsx
  src/index.tsx
  src/pages/Home.tsx
  src/react-app-env.d.ts
  src/shared/Router.tsx
  src/types/supabase.ts
  src/zustand/useLocationStore.ts
  src/zustand/useMapLocationStore.ts
  src/zustand/useMarkerInvisible.ts
  src/zustand/usePostStore.ts
  src/zustand/useSessionStore.ts
  src/zustand/useTabStore.ts
  yarn.lock
Labels: documentation

#112 refactor. mutateAsync -> mutate 변경
  src/components/like/Like.tsx
Labels: documentation

#113 feat. LandingPage 모바일 버전
  package.json
  src/components/landing/style.ts
  yarn.lock
Labels: enhancement

#114 fix. percentage error 수정
  src/components/common/header/style.ts
  src/components/landing/Landing.tsx
Labels: bug

#115 design. 반응형 일부 작업
  public/index.html
  public/logo192.png
  public/logo512.png
  src/assets/miniLogo.svg
  src/components/common/footer/Footer.tsx
  src/components/common/footer/style.ts
  src/components/common/header/Header.tsx
  src/components/common/header/style.ts
  src/components/common/overlay/modal/style.ts
  src/components/common/postItem/style.ts
  src/components/common/switch/style.ts
  src/components/detail/style.ts
  src/components/likesList/style.ts
  src/components/searchList/style.ts
Labels: design

#116 design. 스위치, 버튼 위치 조정
  src/components/common/header/style.ts
  src/components/common/switch/style.ts
  src/components/likesList/style.ts
  src/components/searchList/style.ts
Labels: design

#117 design. 반응형 css 적용
  public/logo192.png
  public/logo512.png
  src/components/common/button/style.ts
  src/components/common/header/Header.hooks.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/HeaderLogin.tsx
  src/components/common/header/HeaderSearch.tsx
  src/components/common/header/style.ts
  src/components/common/overlay/modal/style.ts
  src/components/common/postItem/style.ts
  src/components/common/switch/Switch.tsx
  src/components/common/switch/style.ts
  src/components/detail/style.ts
  src/components/globeSearch/GlobeSearch.tsx
  src/components/globeSearch/style.ts
  src/components/likesList/style.ts
  src/components/post/Post.ContentsSection.tsx
  src/components/post/Post.UploadBox.tsx
  src/components/post/Post.tsx
  src/components/post/style.ts
  src/components/searchList/SearchList.SessionDependentView.tsx
  src/components/searchList/style.ts
  src/index.css
Labels: design

#119 design. 반응형 수정
  src/components/common/header/style.ts
  src/components/common/postItem/style.ts
  src/components/detail/style.ts
  src/components/globe/Globe.tsx
  src/components/globe/style.ts
  src/components/post/Post.ContentsSection.tsx
  src/components/post/style.ts
  src/index.css
Labels: design

#120 design. post 닫기 버튼 border 색 수정 & 확대 방지
  public/index.html
  src/components/common/header/style.ts
  src/components/globe/Globe.tsx
Labels: design

#121 feat. 모바일 게시글 편집 시 리스트 모달 닫기
  src/components/detail/Detail.tsx
Labels: enhancement, fix

#122 Dev to main 3
  public/index.html
  src/components/common/header/style.ts
  src/components/common/postItem/style.ts
  src/components/detail/Detail.tsx
  src/components/detail/style.ts
  src/components/globe/Globe.tsx
  src/components/globe/style.ts
  src/components/post/Post.ContentsSection.tsx
  src/components/post/style.ts
  src/index.css
Labels: documentation

#123 docs. 메타데이터 추가
  public/index.html
Labels: documentation

#124 Dev to main (og tag)
  public/index.html
Labels: documentation

#125 fix. 연타방지
  src/components/post/Post.tsx
  src/components/post/Post.util.tsx
Labels: fix

#126 Dev to main 4
  src/components/post/Post.tsx
  src/components/post/Post.util.tsx
Labels: documentation

#128 design. post 닫기 버튼 호버 color 수정
  src/components/common/header/style.ts
Labels: design

#129 Dev to main
  src/components/common/header/style.ts
Labels: documentation

#131 Dev to main
  src/components/likesList/LikesList.tsx
Labels: documentation

#132 feat.상세모달 열린 채로 스위치 이동하면 모달 닫힘
  src/components/common/header/Header.hooks.tsx
  src/components/common/header/Header.tsx
Labels: enhancement

#133 Dev
  src/components/common/header/Header.hooks.tsx
  src/components/common/header/Header.tsx
Labels: enhancement

#134 design. 디자인 회의 반영
  README.md
  src/assets/pin/pinLargeFocus.svg
  src/components/common/footer/style.ts
  src/components/common/switch/Switch.tsx
  src/components/common/switch/style.ts
  src/components/globeSearch/GlobeSearch.tsx
  src/components/globeSearch/style.ts
  src/components/post/Post.ContentsSection.tsx
  src/components/post/style.ts
  src/index.css
Labels: design

#136 refactor. like 컴포넌트 함수, 훅 분리
  src/components/like/Like.hooks.ts
  src/components/like/Like.tsx
  src/zustand/mutations/useLikeMutation.ts
Labels: documentation

#137 Feat: 파일 형식을 제외하면 Toast 메시지 등장
  src/components/likesList/LikesList.tsx
  src/components/post/Post.tsx
Labels: enhancement

#138 Dev to Main
  src/components/like/Like.hooks.ts
  src/components/like/Like.tsx
  src/components/likesList/LikesList.tsx
  src/components/post/Post.tsx
  src/zustand/mutations/useLikeMutation.ts
Labels: documentation

#139 Feat. Mobile ZoomSize 증가
  src/components/globeSearch/GlobeSearch.tsx
Labels: enhancement

#140 feat. 글 작성하기 tooltip 추가
  src/components/common/header/HeaderLogin.tsx
  src/components/common/header/style.ts
Labels: enhancement

#142 feat. postId에 맞게 가지고 오기..!!!
  src/api/supabaseDatabase.ts
  src/components/common/overlay/modal/style.ts
  src/components/common/postItem/PostItem.tsx
  src/components/common/postItem/style.ts
  src/components/likesList/LikesList.tsx
  src/components/likesList/style.ts
  src/components/searchList/style.ts
Labels: enhancement

#143 feat. 검색 좋아요 내역대로 데이터 필터링, 검색 결과대로 이동
  src/components/common/header/Header.hooks.tsx
  src/components/globe/Globe.tsx
  src/components/globeCluster/GlobeCluster.tsx
  src/components/likesList/LikesList.tsx
  src/components/searchList/SearchList.tsx
  src/zustand/useLikeStore.ts
  src/zustand/useSearchStore.ts
Labels: enhancement

#145 design. 미리보기 이미지 수정
  src/components/globe/style.ts
Labels: design

#147 Dev to main 10
  src/api/supabaseDatabase.ts
  src/components/common/header/Header.hooks.tsx
  src/components/common/header/HeaderLogin.tsx
  src/components/common/header/style.ts
  src/components/common/overlay/modal/style.ts
  src/components/common/postItem/PostItem.tsx
  src/components/common/postItem/style.ts
  src/components/globe/Globe.tsx
  src/components/globe/style.ts
  src/components/globeCluster/GlobeCluster.tsx
  src/components/globeSearch/GlobeSearch.tsx
  src/components/likesList/LikesList.tsx
  src/components/likesList/style.ts
  src/components/searchList/SearchList.tsx
  src/components/searchList/style.ts
  src/zustand/useLikeStore.ts
  src/zustand/useSearchStore.ts
Labels: documentation

#148 feat. searchList 요소 변경
  src/api/supabaseDatabase.ts
  src/components/common/postItem/PostItem.tsx
  src/components/common/postItem/style.ts
  src/components/searchList/SearchList.SessionDependentView.tsx
  src/components/searchList/SearchList.tsx
  src/components/searchList/SearchList.util.tsx
Labels: documentation

#149 fix. 좋아요 목록에서 취소하면 바로 사라지는 기능 수정
  src/components/common/postItem/PostItem.tsx
  src/components/like/Like.hooks.ts
  src/components/like/Like.tsx
  src/components/likesList/LikesList.tsx
Labels: fix

#150 fix. MY 탭 수정 삭제 바로 반영
  src/components/post/Post.util.tsx
  src/components/searchList/SearchList.util.tsx
  src/pages/Home.tsx
Labels: fix

#151 feat. 좋아요 순으로 정렬하게 하기
  src/api/supabaseDatabase.ts
  src/components/likesList/LikesList.tsx
Labels: enhancement

#152 docs. Styled => St로 변경 GlobeCluster 파일명 변경
  src/components/common/postItem/PostItem.tsx
  src/components/common/postItem/style.ts
  src/components/searchList/SearchList.SessionDependentView.tsx
  src/components/searchList/SearchList.util.tsx
Labels: bug, documentation

#153 design. 모바일 반응형 수정
  src/components/globeSearch/GlobeSearch.tsx
  src/index.css
Labels: design

#155 feat. LikeList 데이터 삭제시 깔끔하게 잘 나오게 하기
  src/api/supabaseDatabase.ts
  src/components/common/postItem/PostItem.tsx
  src/components/common/postItem/style.ts
  src/components/likesList/LikesList.tsx
  src/components/searchList/SearchList.util.tsx
Labels: enhancement

#156 docs. 문서 변경 및 css 변경
  src/components/common/header/Header.tsx
  src/components/common/header/HeaderLogin.tsx
  src/components/common/header/HeaderSearch.tsx
  src/components/common/header/style.ts
  src/components/common/postItem/PostItem.tsx
  src/components/common/postItem/style.ts
  src/components/common/switch/Switch.tsx
  src/components/globe/globe.util.tsx
  src/components/landing/Landing.tsx
  src/setupTests.ts
Labels: documentation, fix

#157 fix. get 오류 및 스타일드 경고 수정
  src/components/common/header/Header.tsx
  src/components/common/switch/Switch.tsx
  src/components/common/switch/style.ts
  src/components/landing/Landing.tsx
  src/components/landing/style.ts
  src/components/post/Post.tsx
Labels: fix

#158 fix. 스타일드 경고 수정
  src/components/common/header/Header.tsx
  src/components/common/header/HeaderLogin.tsx
  src/components/common/header/HeaderSearch.tsx
  src/components/common/header/style.ts
  src/components/globe/Globe.tsx
  src/components/globeCluster/GlobeCluster.util.ts
  src/util/GlobeCluster.tsx
Labels: documentation, fix

#159 Dev to main 12
  src/api/supabaseDatabase.ts
  src/components/common/header/Header.tsx
  src/components/common/header/HeaderLogin.tsx
  src/components/common/header/HeaderSearch.tsx
  src/components/common/header/style.ts
  src/components/common/postItem/PostItem.tsx
  src/components/common/postItem/style.ts
  src/components/common/switch/Switch.tsx
  src/components/common/switch/style.ts
  src/components/globe/Globe.tsx
  src/components/globe/globe.util.tsx
  src/components/globeCluster/GlobeCluster.util.ts
  src/components/landing/Landing.tsx
  src/components/landing/style.ts
  src/components/likesList/LikesList.tsx
  src/components/post/Post.tsx
  src/components/searchList/SearchList.util.tsx
  src/setupTests.ts
  src/util/GlobeCluster.tsx
Labels: documentation

#160 refactor. 폴더 위치 수정
  src/components/like/Like.hooks.ts
  src/hooks/mutations/useLikeMutation.ts
Labels: documentation

#161 refactor. Router 파일 수정
  src/shared/Router.tsx
Labels: documentation

#162 Dev to main 13
  src/components/like/Like.hooks.ts
  src/hooks/mutations/useLikeMutation.ts
  src/shared/Router.tsx
Labels: documentation

#164 feat. 메타데이터 사진 지역 이동 속도 추가
  src/components/like/Like.tsx
  src/components/post/imageUpload/ImageUpload.hooks.ts
Labels: enhancement

#163 dev to main
  README.md
  src/components/like/Like.tsx
  src/components/post/imageUpload/ImageUpload.hooks.ts
Labels: documentation
