Repository oiooeo/glog, pull requests merged in 2023-08, with the labels that each got.

#1 Feat. 구글 로그인 연결
  src/App.tsx
  src/api/supabaseAuth.ts
  src/api/supabaseClient.ts
  src/pages/Home.tsx
Labels: enhancement

#2 feat. 공통 스위치 컴포넌트 작성
  src/components/common/switch/Switch.tsx
  src/components/common/switch/style.ts
Labels: enhancement

#3 Feat. 헤더 컴포넌트 작성
  package.json
  src/App.tsx
  src/api/supabaseAuth.ts
  src/components/common/header/Header.tsx
  src/components/common/header/style.ts
  src/pages/Home.tsx
  src/shared/Router.tsx
  yarn.lock
Labels: enhancement

#5 feat. footer 추가
  src/components/common/footer/Footer.tsx
  src/components/common/footer/style.ts
Labels: enhancement

#7 feat. 지구본UI marker 작업
  public/index.html
  src/components/globe/Globe.tsx
  src/pages/Home.tsx
Labels: enhancement

#8 feat. 공통 모달 (center, left, right)
  src/components/common/overlay/modal/Modal.hooks.tsx
  src/components/common/overlay/modal/Modal.tsx
  src/components/common/overlay/modal/style.ts
  src/types/supabase.ts
Labels: enhancement

#9 feat. 헤더에 스위치 추가, 클릭할 때 마다 활성화 된 탭 콘솔 찍기
  src/components/common/header/Header.tsx
  src/components/common/header/style.ts
  src/components/common/switch/style.ts
Labels: enhancement

#12 feat. 헤더 +, 하트 클릭시 로그인 페이지로 연결
  src/api/supabaseDatabase.ts
  src/components/common/header/Header.tsx
  src/types/supabase.ts
Labels: enhancement

#13 feat. 로그인 했을 때 users DB에 정보 없으면 저장
  src/api/supabaseDatabase.ts
  src/components/common/header/Header.tsx
Labels: enhancement

#15 feat. post 작성 mutation 사용
  src/components/common/button/Button.tsx
  src/components/common/button/style.ts
  src/components/common/header/style.ts
  src/components/common/overlay/modal/Modal.tsx
  src/components/common/overlay/modal/style.ts
  src/components/post/Post.tsx
  src/components/post/style.ts
  src/hooks/useInput.tsx
  src/types/supabase.ts
Labels: enhancement

#16 feat. 글 작성
  src/api/supabaseDatabase.ts
  src/components/common/header/Header.tsx
  src/components/common/overlay/modal/Modal.tsx
  src/components/common/overlay/modal/style.ts
  src/components/globe/Globe.tsx
  src/components/post/Post.tsx
  src/components/post/style.ts
  src/hooks/useSessionStore.ts
  src/types/supabase.ts
  src/zustand/store.ts
Labels: enhancement

#20 feat. supabase 데이터 가져오기
  src/api/supabaseDatabase.ts
  src/components/detail/Detail.tsx
  src/components/detail/style.ts
  src/components/globe/Globe.tsx
  src/shared/Router.tsx
Labels: enhancement

#22 feat. popup 최신 것만 나타내기
  public/index.html
  src/components/globe/Globe.tsx
  yarn.lock
Labels: enhancement

#23 Design.detail
  src/components/detail/Detail.tsx
  src/components/detail/style.ts
  src/components/post/style.ts
Labels: design

#24 feat. 게시글 검색 기능
  src/api/supabaseDatabase.ts
  src/components/common/header/Header.tsx
  src/components/common/header/style.ts
  src/components/common/overlay/modal/style.ts
  src/components/common/postItem/PostItem.tsx
  src/components/globe/style.ts
  src/components/likesList/LikesList.tsx
  src/components/searchList/SearchList.tsx
Labels: enhancement, design

#26 feat. 로그인 시 users DB에 이름, 프로필 사진 저장
  src/api/supabaseDatabase.ts
  src/components/common/header/Header.tsx
  src/types/supabase.ts
Labels: enhancement

#27 feat. my 클릭 login 유도
  src/components/common/header/Header.tsx
Labels: enhancement

#28 feat. 게시글 작성 시 DB에 전체 주소 넣기, 검색에 반영
  src/components/common/header/Header.tsx
  src/components/globe/Globe.tsx
  src/components/post/Post.tsx
  src/components/searchList/SearchList.tsx
  src/types/supabase.ts
  src/zustand/store.ts
Labels: enhancement

#29 feat. 비 로그인시 search 임의의 수만 보이게 하기
  package.json
  src/components/globe/Globe.tsx
  src/components/searchList/SearchList.tsx
  yarn.lock
Labels: enhancement

#30 feat. 디테일 페이지를 미리보기랑 연결
  src/components/common/header/Header.tsx
  src/components/common/overlay/modal/Modal.tsx
  src/components/common/overlay/modal/style.ts
  src/components/detail/Detail.tsx
  src/components/detail/style.ts
  src/components/globe/Globe.tsx
  src/components/globe/preview/Preview.tsx
  src/components/globe/preview/style.ts
  src/shared/Router.tsx
Labels: enhancement

#31 feat. 좋아요 기능 완성
  src/api/supabaseDatabase.ts
  src/components/common/postItem/PostItem.tsx
  src/components/like/Like.tsx
  src/components/like/style.ts
  src/components/likesList/LikesList.tsx
  src/components/searchList/SearchList.tsx
Labels: enhancement

#32 feat. 수정, 삭제 버튼 로그인한 유저한테만 보이게
  src/components/detail/Detail.tsx
  src/components/detail/style.ts
Labels: enhancement

#33 design. 상세 모달 css
  src/components/common/overlay/modal/style.ts
  src/components/detail/Detail.tsx
  src/components/detail/style.ts
Labels: design

#34 feat. 작성자 정보, 상세 모달 열렸을 때 미니 모달 위치 조정
  src/api/supabaseDatabase.ts
  src/components/detail/Detail.tsx
  src/components/detail/style.ts
  src/components/globe/Globe.tsx
Labels: enhancement, design

#35 refactor. Globe.tsx refactoring, Preview 폴더 삭제
  src/api/supabaseDatabase.ts
  src/components/common/overlay/modal/style.ts
  src/components/detail/style.ts
  src/components/globe/Globe.tsx
  src/components/globe/preview/Preview.tsx
  src/components/globe/preview/style.ts
  src/pages/Home.tsx
  src/pages/MyPage.tsx
Labels: documentation, design

#36 design. 로고, 핀 svg 파일 업로드
  src/assets/logo.svg
  src/assets/pin/pinFocus.svg
  src/assets/pin/pinLarge.svg
  src/assets/pin/pinSmall.svg
  src/components/common/header/Header.tsx
Labels: design

#37 feat. 토스트 알림
  package.json
  src/components/common/header/Header.tsx
  src/components/post/Post.tsx
  src/index.css
  yarn.lock
Labels: enhancement, design

#38 feat. 좋아요 리스트
  src/api/supabaseDatabase.ts
  src/components/likesList/LikesList.tsx
Labels: enhancement

#39 feat. 6개 이미지 마커 제외한 나머지 게시글 핀 마커 찍기
  src/components/globe/Globe.tsx
  src/components/globe/style.ts
  src/pages/Home.tsx
Labels: enhancement

#40 fix. 좋아요 함수 수정
  src/api/supabaseDatabase.ts
  src/components/globe/Globe.tsx
  src/components/like/Like.tsx
Labels: bug

#41 feat. 좋아요, 검색 목록 게시글 hover 효과, 클릭했을 때 상세 내용 보이기
  src/components/common/overlay/modal/style.ts
  src/components/common/postItem/PostItem.tsx
  src/components/common/postItem/style.ts
  src/components/detail/Detail.tsx
  src/components/detail/style.ts
  src/components/globe/Globe.tsx
  src/hooks/useOnClickOutSide.ts
Labels: enhancement

#42 feat. 삭제 로직
  src/api/supabaseDatabase.ts
  src/components/detail/Detail.tsx
  src/components/detail/style.ts
  src/index.css
Labels: enhancement

#43 feat. 게시글 작성시 핀찍는 화면
  src/components/common/header/Header.tsx
  src/components/post/Post.tsx
  src/components/post/pin.png
  src/components/post/style.ts
Labels: enhancement

#44 refactor. 삭제 로직을 mutation으로 리팩토링
  src/components/detail/Detail.tsx
Labels: help wanted, wontfix

#45 design. 헤더, 푸터 디자인
  src/components/common/footer/style.ts
  src/components/common/header/Header.tsx
  src/components/common/header/style.ts
  src/components/common/overlay/modal/style.ts
  src/components/common/postItem/PostItem.tsx
  src/components/common/postItem/style.ts
  src/components/common/switch/Switch.tsx
  src/components/common/switch/style.ts
  src/components/detail/style.ts
  src/components/globe/Globe.tsx
  src/components/globe/style.ts
  src/components/like/Like.tsx
  src/components/like/style.ts
  src/components/post/Post.tsx
  src/components/searchList/SearchList.tsx
Labels: design

#46 design. 지구, 글 작성 위주 + 전체적으로 수정
  src/api/supabaseDatabase.ts
  src/components/common/button/style.ts
  src/components/common/header/Header.tsx
  src/components/common/overlay/modal/style.ts
  src/components/common/switch/Switch.tsx
  src/components/common/switch/style.ts
  src/components/globe/Globe.tsx
  src/components/globe/style.ts
  src/components/likesList/LikesList.tsx
  src/components/post/Post.tsx
  src/components/post/pin.png
  src/components/post/style.ts
  src/zustand/store.ts
Labels: design

#47 design. 상세 모달, 글 작성
  src/api/supabaseDatabase.ts
  src/components/common/footer/style.ts
  src/components/detail/Detail.tsx
  src/components/detail/style.ts
  src/components/globe/style.ts
  src/components/post/Post.tsx
  src/components/post/style.ts
  src/index.css
Labels: design

#48 feat. 탐색 탭에서 전체공개인 글만 가져오기, 본인이 작성한 글은 다 가져오기
  src/api/supabaseDatabase.ts
  src/components/common/header/Header.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#49 feat. 글 작성 시 핀 모두 안 보이게
  src/components/common/header/Header.tsx
  src/components/globe/Globe.tsx
  src/components/post/Post.tsx
  src/zustand/store.ts
Labels: enhancement

#50 feat. SearchBox && Like, SearchList 무한 스크롤 완성
  src/api/mapbox.ts
  src/components/common/header/Header.tsx
  src/components/common/postItem/PostItem.tsx
  src/components/common/postItem/style.ts
  src/components/globe/Geo.jsx
  src/components/globe/SearchBox.tsx
  src/components/globe/style.ts
  src/components/likesList/LikesList.tsx
  src/components/likesList/style.ts
  src/components/post/Post.tsx
  src/components/searchList/SearchList.tsx
  src/components/searchList/style.ts
Labels: enhancement

#51 feat. 사진 용량 줄이기
  package.json
  src/components/post/Post.tsx
  yarn.lock
Labels: enhancement

#52 feat. heic 파일을 Jpg로 변환
  package.json
  src/components/post/Post.tsx
  yarn.lock
Labels: enhancement

#53 feat. 목록에서 글 클릭 시 핀 주황색
  src/components/common/header/Header.tsx
  src/components/common/postItem/PostItem.tsx
  src/components/globe/Globe.tsx
  src/components/globe/style.ts
  src/hooks/useOnClickOutSide.ts
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/shared/Router.tsx
  src/zustand/store.ts
Labels: enhancement

#55 refactor. 지구 마커 리팩토링
  src/components/globe/Globe.marker.tsx
  src/components/globe/Globe.tsx
  src/components/globe/globe.util.tsx
  src/components/globe/style.ts
  src/types/supabase.ts
Labels: documentation

#56 design. 글 작성 시 지역 검색창
  src/components/globe/style.ts
  src/components/globeSearch/GlobeSearch.tsx
  src/components/globeSearch/style.ts
  src/components/post/Post.tsx
Labels: design

#57 cluster작업 완료
  package.json
  src/assets/pin/LargePin.png
  src/assets/pin/mideumPin.png
  src/assets/pin/smallPin.png
  src/components/globe/Globe.tsx
  src/components/globe/GlobeCluster.tsx
  src/components/globeSearch/GlobeSearch.tsx
  yarn.lock
Labels: enhancement

#58 feat. 수정 기능 구현
  src/api/supabaseDatabase.ts
  src/components/common/header/Header.tsx
  src/components/detail/Detail.tsx
  src/components/post/Post.tsx
Labels: enhancement

#59 chore. 사진 input 코드 수정 및 불필요한 코드 삭제
  src/components/post/Post.tsx
Labels: enhancement

#60 feat. 현재 시점으로 위치 등록
  src/components/common/button/style.ts
  src/components/common/header/Header.tsx
  src/components/common/header/style.ts
  src/components/detail/Detail.tsx
  src/components/globe/Globe.marker.tsx
  src/components/globe/Globe.tsx
  src/components/globe/GlobeCluster.tsx
  src/components/globe/globe.util.tsx
  src/components/post/Post.tsx
  src/components/post/style.ts
  src/zustand/store.ts
Labels: enhancement

#62 docs. 리드미 작성
  README.md
Labels: design

#63 feat. 글 작성, 수정 후 뜨는 모달 정보 오류 수정 / 수정 중에는 지구 못 돌리게 수정
  src/api/supabaseDatabase.ts
  src/components/detail/Detail.tsx
  src/components/globe/Globe.tsx
  src/components/post/Post.tsx
  src/components/post/style.ts
  src/index.css
Labels: enhancement

#64 Feat/cluster
  src/api/supabaseDatabase.ts
  src/components/common/header/Header.tsx
  src/components/globe/Globe.tsx
  src/components/globe/GlobeCluster.tsx
  src/components/searchList/SearchList.tsx
Labels: enhancement

#65 feat. 메타 데이터 불러와서 좌표 찍기, 삭제 버튼 추가
  package.json
  src/components/globe/Globe.tsx
  src/components/post/Post.tsx
  yarn.lock
Labels: enhancement

#66 docs. SearchList 문서 변경
  src/components/searchList/SearchList.tsx
Labels: bug

#67 feat. 무한 스크롤 로딩 컴포넌트
  src/components/likesList/LikesList.tsx
  src/components/likesList/style.ts
  src/components/searchList/SearchList.tsx
  src/components/searchList/style.ts
Labels: enhancement

#68 feat. 사진 업로드 시 로딩중 화면 띄우기
  src/components/globe/GlobeCluster.tsx
  src/components/globeSearch/GlobeSearch.tsx
  src/components/post/Post.tsx
  src/components/searchList/SearchList.tsx
Labels: enhancement

#69 design. 회의 의견 반영 후 수정
  src/components/common/footer/style.ts
  src/components/common/header/Header.tsx
  src/components/post/Post.tsx
  src/components/post/style.ts
  src/components/searchList/SearchList.tsx
Labels: design

#71 refactor. zustand store 분리
  package.json
  src/components/common/button/buttonExample.tsx
  src/components/common/header/Header.tsx
  src/components/common/overlay/dialog/Dialog.hooks.tsx
  src/components/common/overlay/dialog/Dialog.tsx
  src/components/common/postItem/PostItem.tsx
  src/components/detail/Detail.tsx
  src/components/globe/Globe.tsx
  src/components/globeSearch/GlobeSearch.tsx
  src/components/like/Like.tsx
  src/components/likesList/LikesList.tsx
  src/components/post/Post.tsx
  src/components/searchList/SearchList.tsx
  src/hooks/useOnClickOutSide.ts
  src/pages/Home.tsx
  src/zustand/store.ts
  src/zustand/useClickedPostStore.ts
  src/zustand/useLocationStore.ts
  src/zustand/useMapLocationStore.ts
  src/zustand/usePostStore.ts
  src/zustand/useSessionStore.ts
  src/zustand/useTabStore.ts
Labels: documentation

#72 refactor. detail 파일 수정
  src/components/detail/Detail.tsx
  src/components/detail/style.ts
Labels: enhancement

#75 refactor. SearchList 파일 수정
  src/components/searchList/SearchList.tsx
  src/components/searchList/SearchList.until.tsx
Labels: documentation

#77 refactor. fetchMyPosts 함수 분리
  src/components/globe/Globe.content.ts
  src/components/globe/Globe.tsx
  src/pages/Home.tsx
Labels: documentation

#78 refactor. Globe 파일 수정
  src/components/globe/Globe.tsx
  src/components/globe/GlobeCluster.tsx
  src/components/globe/globe.util.tsx
Labels: documentation

#79 refactor. Globe 파일 수정
  src/assets/pin/LargePin.png
  src/assets/pin/clusterFive.png
  src/assets/pin/clusterTen.png
  src/assets/pin/clusterTwenty.png
  src/assets/pin/mideumPin.png
  src/assets/pin/unclusterPin.png
  src/components/globe/Globe.tsx
  src/components/globe/GlobeCluster.tsx
  src/components/globe/GlobeCluster.util.ts
  src/components/searchList/SearchList.SessionDependentView.tsx
  src/components/searchList/SearchList.tsx
  src/pages/Home.tsx
Labels: documentation, enhancement

#80 refactor. like mutation 함수, supabase 함수 분리
  src/api/supabaseDatabase.ts
  src/components/detail/Detail.tsx
  src/components/like/Like.hooks.ts
  src/components/like/Like.tsx
  src/components/likesList/LikesList.tsx
  src/components/likesList/style.ts
Labels: documentation

#81 Feat/common/header
  src/components/common/header/Header.tsx
  src/components/common/header/HeaderLogin.tsx
  src/components/common/header/HeaderSearch.tsx
  src/components/common/header/useHeaderModal.tsx
Labels: documentation

#82 refactor. post 컴포넌트 리팩토링
  src/components/post/Post.ContentsSection.tsx
  src/components/post/Post.UploadBox.tsx
  src/components/post/Post.tsx
  src/hooks/useImageUpload.ts
Labels: documentation

#83 fix. 수정 이미지 안 불러와지는 거 고침
  src/components/post/Post.UploadBox.tsx
  src/components/post/Post.tsx
  src/hooks/useImageUpload.ts
Labels: documentation

#84 fix. 좋아요 오류 해결
  src/api/supabaseDatabase.ts
  src/components/like/Like.hooks.ts
  src/components/like/Like.tsx
  src/types/supabase.ts
Labels: fix

#85 fix. 게시글 삭제 후 작성중 상태 변경
  src/components/common/header/HeaderSearch.tsx
  src/components/post/Post.UploadBox.tsx
  src/components/post/Post.tsx
Labels: fix

#86 fix. deatil 시간 수정
  src/components/detail/Detail.tsx
Labels: fix

#87 refactor. Post(Mutation) && Post(util) 생성
  src/components/common/header/Header.tsx
  src/components/common/header/HeaderSearch.tsx
  src/components/common/postItem/PostItem.tsx
  src/components/post/Post.ContentsSection.tsx
  src/components/post/Post.tsx
  src/components/post/Post.util.tsx
Labels: documentation

#88 feat. myPage 이동시 수정, 삭제 해결
  src/pages/Home.tsx
Labels: enhancement

#89 feat. 게시글 바깥 클릭 시 포커스 핀 삭제
  src/components/common/header/HeaderLogin.tsx
  src/components/common/header/useHeaderModal.tsx
  src/components/common/overlay/modal/style.ts
  src/components/common/postItem/PostItem.tsx
  src/components/globe/Globe.tsx
  src/components/globe/GlobeCluster.tsx
  src/components/globe/globe.util.tsx
  src/components/likesList/style.ts
  src/hooks/useOnClickOutSide.ts
  src/pages/Home.tsx
  src/zustand/useClickedPostStore.ts
  src/zustand/useMarkerInvisible.ts
Labels: enhancement

#90 refactor. LikesList 파일 수정
  src/components/likesList/LikesList.tsx
Labels: documentation

#91 feat. 공통 로더
  src/assets/loader/loaderBg.svg
  src/assets/loader/loaderLeft.svg
  src/assets/loader/loaderRight.svg
  src/components/common/loader/Loader.tsx
  src/components/common/loader/style.ts
Labels: enhancement

#92 design. 로더 애니메이션 수정
  src/components/common/loader/style.ts
  src/components/post/Post.UploadBox.tsx
Labels: design

#93 design. 디자인 수정
  package.json
  public/favicon.ico
  public/favicon.svg
  public/index.html
  src/components/detail/Detail.tsx
  src/components/detail/style.ts
  src/components/likesList/LikesList.tsx
  src/components/post/Post.UploadBox.tsx
  src/components/post/style.ts
  src/components/searchList/SearchList.SessionDependentView.tsx
  yarn.lock
Labels: design
